export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Process } from './Process';
export { default as Capabilities } from './Capabilities';
export { default as Pricing } from './Pricing';
export { default as Industries } from './Industries';
export { default as Compliance } from './Compliance';
export { default as CTASection } from './CTASection';
export { default as Footer } from './Footer';
